package com.example.swipeflix.models;

public enum Genre {
    ACTION, ADVENTURE, HISTORY, WESTERN, THRILLER, DRAMA, HORROR, COMEDY, ROMANCE, MYSTERY, CRIME, DOCUMENTARY, FANTASY, SCIENCE_FICTION, TV_MOVIE, FAMILY, FOREIGN, ANIMATION, UNKNOWN
}
